title: "A cabeça da Mákina"
author: "Flávio Martins"
description: "Filosofia, tecnologia, educação e notas breves."
url: "https://makinadeideias.github.io"
baseurl: "/blog"

# Bloqueia posts com data no futuro
future: false

timezone: America/Sao_Paulo
markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed