title: "A cabeça da Mákina"
description: "Notas, reflexões e ensaios"
url: "https://makinadeideias.github.io"
baseurl: "/blog"

# Bloqueia posts com datas futuras
future: false

timezone: America/Sao_Paulo
markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed